repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Rustfmt (formatage)
        files: ^back/
      - id: clippy
        name: Clippy (linter)
        files: ^back/
        args: ["--", "-D", "warnings"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        name: Conventional commits check
        stages: [commit-msg]